config/routes.rb
Rails.application.routes.draw do

  post 'heart', to: 'hearts#heart'#, via: :food
  match 'unheart', to: 'hearts#unheart', via: :delete

  resources :hearts
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  
  get 'sessions/create'

  get 'sessions/destroy'

  root 'foods#new'
  get 'foods/home' => 'foods#home'
  get 'foods/home/:id' => 'foods#home'
  get 'foods/show_all' => 'foods#show_all'
  get 'foods/about' => 'foods#about'
  get 'foods/search' => 'foods#search'
  post 'foods/search' => 'foods#search'
  post 'foods/edit' => 'foods#edit'
  post 'foods/update' => 'foods#update'
  get 'foods/add'

  resources :foods
  
  

end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :food

  
  belongs_to :user


  validates :user_id, uniqueness: {scope: :food_id}

  
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  respond_to :js

  def heart
    if current_user.nil?
      redirect_to '/auth/facebook'
    else
      @user = current_user
      @food = Food.find(params[:food_id])
      @user.heart!(@food)
    end
  end

  def unheart
    @user = current_user
    @heart = @user.hearts.find_by_food_id(params[:food_id])
    @food = Food.find(params[:food_id])
    @heart.destroy!
  end
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/views/hearts/_button.html.erb
<div class="thumbnail">
	<img src="http://www.brake.eu/images/home1.jpg" alt="">
	<div class="caption" >
		<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
	
		<prize class="pull-right"><%= '%.2f' % food.price %></prize>
		<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

		<foodNamez><%= food.food_name %></foodNamez>
	</div>
	<desc>
		<div>
		<link href="https://fonts.googleapis.com/css?family=Ubuntu+Condensed" rel="stylesheet">

				<detz><strong>Resto Name:</strong>  <%= food.resto_name %></detz>
				
				<detz><br /> <strong> Location:</strong> <%= food.address %></detz>
				
				<detz><br /> <strong> Description:</strong> <%= food.description %></detz>
		</div>			
	</desc>
<br>
<!--
<div align="pull-right" ><button class= "heart" type="button" id="like3" rel="like" style="border:none; float: right;" >
<label class="likeCount" id="likeCount3" >24</label>
</div> -->

	<link href="https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed" rel="stylesheet">

	<tagz>
		<%= 'Contributors:' %>
		<%= food.all_contributors %>
	</tagz>
<br>	

	<tagz style ="padding-bottom: 1px">
		<%= 'Tags:' %>
		<%= food.all_tags %>
	</tagz>
<br>
<br>
<br>

<div style="float: right;position:relative;bottom:33px; font-size: 1.5em;padding-right: 1em;">
	<%= food.hearts.count %>
</div>	
<div style="float: right;position:relative;bottom:28px;"> 

	<% if current_user and current_user.heart?(food) %>
		<%= button_to "❤", unheart_path(food_id: food.id), remote: true, method: :delete, class: "toggle-unheart" %>
	<% else %>
		<% session[:back_to] = request.env['PATH_INFO'] %>
		<% session[:search] = params[:search] %>
		<%= button_to "❤", heart_path(food_id: food.id), remote: true, class: "toggle-heart" %>
	<% end %>
</div>
<div style="float: right;position:relative;bottom:30px;right: 10px;">
	<%= button_to foods_edit_path(food_id: food.id), class: "btn btn-info btn-lg", style: "font-size: 16px;padding: 7px;border:none;line-height:0;" do %>
	    <span class="glyphicon glyphicon-pencil" style="font-size: 16px;padding: none;"></span> Edit
	<% end %>
</div>
</div>

app/views/hearts/heart.js.erb
$('div#<%= dom_id(@food) %>').html('<%= j render partial: "button", locals: {food: @food} %>');

app/views/hearts/unheart.js.erb
$('div#<%= dom_id(@food) %>').html('<%= j render partial: "button", locals: {food: @food} %>');