config/routes.rb
Rails.application.routes.draw do

  post 'heart', to: 'hearts#heart'#, via: :food
  match 'unheart', to: 'hearts#unheart', via: :delete

  resources :hearts
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  
  get 'sessions/create'

  get 'sessions/destroy'

  root 'foods#new'
  get 'foods/home' => 'foods#home'
  get 'foods/home/:id' => 'foods#home'
  get 'foods/show_all' => 'foods#show_all'
  get 'foods/about' => 'foods#about'
  get 'foods/search' => 'foods#search'
  post 'foods/search' => 'foods#search'
  post 'foods/edit' => 'foods#edit'
  post 'foods/update' => 'foods#update'
  get 'foods/add'

  resources :foods
  
  

end

app/models/food.rb
class Food < ApplicationRecord
  has_many :hearts, dependent: :destroy
  has_many :users, through: :hearts

  has_many :contributors, dependent: :destroy
  has_many :users, through: :contributors

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :food_name, presence: true, format: { without: /\A\d+\Z/i, message: 'must not contain only numbers' }
  validates :price, presence: true, numericality: true
  validates :resto_name, presence: true, format: { without: /\A\d+\Z/i, message: 'must not contain only numbers' }
  validates :address, presence: true, format: { without: /\A\d+\Z/i, message: 'must not contain only numbers' }
  validates :all_tags, presence: true, format: { with: /\A([a-z]+)(,\s*[a-z]+)*\Z/i, message: 'Invalid format. Please follow the example above.' }
  validates :description, presence: true, format: { without: /\A\d+\Z/i, message: 'must not contain only numbers' }

  def self.contributed_by(name)
    # TODO: create contributors
    User.find_by(name: name).foods
  end

  def contributor=(name)
    # TODO: create contributors
    users << User.where(name: name)
    #self.contributions = names.split(',').map do |name|
    #  Tag.where(name: name).first_or_create!
    #end
  end

  def all_contributors
    users.map(&:name).join(', ')
  end

  def self.tagged_with(name)
  	Tag.find_by(name: name).foods
  end

  def all_tags=(names)
  	self.tags = names.split(',').map do |name|
  	  Tag.where(name: name).first_or_create!
  	end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end

  def self.search(search)
    num_search = -1
    if numeric? search
      num_search = search.to_f
    end
    Food.joins(:tags).where('food_name ILIKE ? OR price = ? OR resto_name ILIKE ? OR description ILIKE ? OR address ILIKE ? OR name ILIKE ?', ("%" +search + "%"), (num_search), ("%" + search + "%"), ("%" + search + "%"), ("%" + search + "%"), ("%" + search + "%")).distinct
  end

  private

  def self.numeric?(string)
    # `!!` converts parsed number to `true`
    !!Kernel.Float(string) 
    rescue TypeError, ArgumentError
    false
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  #before_action :authenticate_user!, only: [:new, :vote]
  respond_to :js, :json, :html

  def food_params
    params.require(:food).permit(:food_name, :price, :resto_name, :description, :address, :all_tags, :all_contributors)
  end
  
  def about
    
  end

  def new
    redirect_to foods_home_path
  end
    
  def home
    session[:name_asc] = true
    session[:likes_asc] = true
    session[:price_asc] = true
  end

  def show_all
    if params[:sort_by] == 'name'
      if session[:name_asc] == true
        @foods = Food.all.to_a.sort! {|a,b| a.food_name <=> b.food_name}
        session[:name_asc] = false
      elsif session[:name_asc] == false
        @foods = Food.all.to_a.sort! {|a,b| b.food_name <=> a.food_name}
        session[:name_asc] = true
      end
    elsif params[:sort_by] == 'likes'
      if session[:likes_asc] == true
        @foods = Food.all.to_a.sort! {|a,b| a.hearts.count <=> b.hearts.count}
        session[:likes_asc] = false
      elsif session[:likes_asc] == false
        @foods = Food.all.to_a.sort! {|a,b| b.hearts.count <=> a.hearts.count}        
        session[:likes_asc] = true
      end
    elsif params[:sort_by] == 'price'
      if session[:price_asc] == true
        @foods = Food.all.to_a.sort! {|a,b| a.price <=> b.price}
        session[:price_asc] = false
      elsif session[:price_asc] == false
        @foods = Food.all.to_a.sort! {|a,b| b.price <=> a.price}
        session[:price_asc] = true
      end
    else
      @foods = Food.all
    end
  end
  
  def index
    
  end

  def search
  #render plain: params[:search].inspect
    session[:search] = params[:search] 
    if params[:search].nil? or params[:search].empty?
      @foods = Food.all
    elsif params[:sort_by] == 'name'
      if session[:name_asc] == true
        @foods = Food.search(params[:search]).to_a.sort! {|a,b| a.food_name <=> b.food_name}
        session[:name_asc] = false
      elsif session[:name_asc] == false
        @foods = Food.search(params[:search]).to_a.sort! {|a,b| b.food_name <=> a.food_name}
        session[:name_asc] = true
      end
    elsif params[:sort_by] == 'likes'
      if session[:likes_asc] == true
        @foods = Food.search(params[:search]).to_a.sort! {|a,b| a.hearts.count <=> b.hearts.count}
        session[:likes_asc] = false
      elsif session[:likes_asc] == false
        @foods = Food.search(params[:search]).to_a.sort! {|a,b| b.hearts.count <=> a.hearts.count}
        session[:likes_asc] = true
      end
    elsif params[:sort_by] == 'price'
      if session[:price_asc] == true
        @foods = Food.search(params[:search]).to_a.sort! {|a,b| a.price <=> b.price}
        session[:price_asc] = false
      elsif session[:price_asc] == false
        @foods = Food.search(params[:search]).to_a.sort! {|a,b| b.price <=> a.price}
        session[:price_asc] = true
      end
    else
      @foods = Food.search(params[:search])  
    end
    if @foods.empty?
      flash[:warning] = "Result not found"
    end
  end
    
  def create
    # render plain: params[:food].inspect
    @food = Food.new(food_params)
    @food.save
    @food.users << current_user
    redirect_to foods_home_path
  end
  
  def update
    food = Food.update(session[:food_id], food_params)
    food.save
    if not food.users.include? current_user
      food.users << current_user
    end
    redirect_to foods_home_path
  end

  def edit

  end

  def destroy
        
  end
  
  def show
    redirect_to foods_search_path
  end

=begin
  def heart
    if !current_user.heart? @food
      @food.hearted_by current_user
    elsif current_user.heart? @food
      @food.unhearted_by current_user
    end
  end
=end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/about.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

   
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-casual.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12" align="center">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>Us</strong>
                    </h2>
                    <hr>

                </div>
                
                <p>
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Foodesire is a web app dedicated for searching food located around Tacloban City area. We are pleased to offer the convenience of finding the food that will satisfy your cravings with the use of our app.
                </p>

        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12" align="center">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong>Developers</strong>
                    </h2>
                    <hr>
         
                   <img src="https://image.ibb.co/nKdrha/final_Developers.png" alt="final_Developers" border="0">


                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

   

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

app/views/foods/add.html.erb
<% if current_user %>
<h1></h1>
<div class="container">
<div class="row" align="center">

  <div class="box">


     <div class="col-lg-12">
       <hr>
        <h2 class="intro-text text-center">Add
          <strong>Food</strong>
        <br>
        </h2>
<hr>
<br>
<br>

<div class="alert alert-info">
  <strong>Attention!</strong> Image upload feature is not yet supported but it will be included in the next release of this app so be on update.
</div>

<div class="container">
<div class="col-md-9 personal-info">
<% @food = Food.new %>
<%= form_for(Food.new, :validate => true, :url => {action: "create"}, html: {class: 'inline_validator_form'}) do |f| %>
        
        
          
          
            <div class="form-group" class="field_with_errors">
              <label class="col-lg-3 control-label">Food name:</label>
              <div class="col-lg-8">
                <%= f.text_field :food_name, :class => "form-control" %>
              </div>
            </div>
            <br>
            <br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Price (in &#8369;):</label>
              <div class="col-lg-8">
                <%= f.text_field :price, :class => "form-control" %>
              </div>
            </div>
            <br>
            <br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Restaurant name:</label>
              <div class="col-lg-8">
                <%= f.text_field :resto_name, :class => "form-control"  %>
              </div>
            </div>
            <br><br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Location:</label>
              <div class="col-lg-8">
                <%= f.text_field :address, :class => "form-control"  %>
              </div>
            </div>
            <br><br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Tags (ex. pizza,meal):</label>
              <div class="col-lg-8">
                <%= f.text_field :all_tags, :class => "form-control"  %>
              </div>
            </div>
            <br><br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Description:</label>
              <div class="col-lg-8">
                <%= f.text_area :description, :class => "form-control"  %>
              </div>
            </div>
             <br>
            <br>
            <br>
<!--            <div class="form-group">
             <br>
            <br>
            <br>
              <label class="col-md-3 control-label">Image:</label>
              <div class="col-md-8">
                <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
                <br>
            <br>
            <br>
            <input type="file" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label"></label>
              <div class="col-md-8">
              <br>
            <br>
            <br>
-->            

    <%= f.submit "Add Food", :class => "btn btn-primary" %>
    <%= button_tag "Reset", type: :reset, :class => "btn btn-secondary" %>

<% end %>


</div>


           

                
              </div>

            </div>

                  </div>
              </div>
          </div>
  </div>
<% else %>
  <% session[:back_to] = request.env['PATH_INFO'] %>
  <script type="text/javascript">
      window.location.href="/auth/facebook"
  </script>
<% end %>
    

app/views/foods/edit.html.erb
<% session[:food_id] = params[:food_id] %>
<% if current_user %>
<h1></h1>
<div class="container">
<div class="row" align="center">

            <div class="box">


                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Edit
                        <strong>Food</strong>
                         <br>
                    </h2>
                    <hr>
                              <br>
          <br>

                    <p></p>

                    <a>

<div class="alert alert-info">
  <strong>Attention!</strong> Image upload feature is not yet supported but it will be included in the next release of this app so be on update.
</div>

<% food = Food.where('id = ?', params[:food_id]).first %>
<%= form_for(food, :validate => true, :url => {action: "update"}, html: {class: 'inline_validator_form'}) do |f| %>

              <div class="form-group" class="field_with_errors">
              <label class="col-lg-3 control-label">Food name:</label>
              <div class="col-lg-8">
                <%= f.text_field :food_name, :class => "form-control" %>
              </div>
            </div>
            <br>
            <br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Price (in &#8369;):</label>
              <div class="col-lg-8">
                <%= f.text_field :price, :class => "form-control" %>
              </div>
            </div>
            <br>
            <br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Restaurant name:</label>
              <div class="col-lg-8">
                <%= f.text_field :resto_name, :class => "form-control"  %>
              </div>
            </div>
            <br><br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Location:</label>
              <div class="col-lg-8">
                <%= f.text_field :address, :class => "form-control"  %>
              </div>
            </div>
            <br><br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Tags (ex. pizza,meal):</label>
              <div class="col-lg-8">
                <%= f.text_field :all_tags, :class => "form-control"  %>
              </div>
            </div>
            <br><br>
            <br>
            <div class="form-group">
              <label class="col-lg-3 control-label">Description:</label>
              <div class="col-lg-8">
                <%= f.text_area :description, :class => "form-control"  %>
              </div>
            </div>
             <br>
            <br>
            <br>
<!--            <div class="form-group">
             <br>
            <br>
            <br>
              <label class="col-md-3 control-label">Image:</label>
              <div class="col-md-8">
                <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
                <br>
            <br>
            <br>
            <input type="file" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label"></label>
              <div class="col-md-8">
              <br>
            <br>
            <br>
-->           

    <%= f.submit "Edit Food", :class => "btn btn-primary" %>
    <%= button_tag "Reset", type: :reset, :class => "btn btn-secondary" %>
<% end %>


                    </a>
                  </div>
              </div>
          </div>
  </div>
<% else %>
  <% session[:back_to] = request.env['PATH_INFO'] %>
  <script type="text/javascript">
      window.location.href="/auth/facebook"
  </script>
<% end %>
    

app/views/foods/home.html.erb
  <div align="center">
  <div class="text"></div>
  <br>
  <br>
  <%= form_tag foods_search_path, :method => 'get' do %>
  <input type="text" id="search" name="search" class="button" placeholder="Search"/>
  <%end%>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <script src='http://use.edgefonts.net/amaranth.js'></script>
</div>
</div>


<div class="container">
<div class="box">
<div class="row">
  <div class="col-lg-12" align="center">
   <hr>
                    <h2 class="intro-text text-center">Most Liked
                        <strong>Food</strong>
                    </h2>
                    <hr>
<br>
</div>
<div class = "row">
<ul class= "products">
<% foods = Food.joins(:hearts).select("foods.*, count(hearts.id) as hcount").group("foods.id").order("hcount DESC") %>
          <% foods[0...3].each do |f|  %>  
  
  <li>
    <%= div_for f do %>   
      <%= render :partial => 'hearts/button', :locals => {:food => f} %>
    <% end %>
  </li>

  <% end %>
</div>
</div>
</div>
</div>
</div>

<div class = "container">
<div class="box">
<div class = "row">
<div class="col-lg-12" align="center">
                    <hr>
                    <h2 class="intro-text text-center">Recently Added
                        <strong>Food</strong>
                        
                    </h2>
                    <hr>
                    <br>

</div>
<% foods = Food.order("created_at").last(3) %>
                       <% foods[0...3].each do |f|  %>  
  
     <%= div_for f, :class=>"col-sm-4 col-lg-4 col-md-4" do %>
     
    <%= render :partial => 'hearts/button', :locals => {:food => f} %>
  <% end %>



  <% end %>


</div>
</div>
</div>

    <!-- jQuery -->
    <script src="https://blackrockdigital.github.io/startbootstrap-business-casual/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-business-casual/js/bootstrap.min.js"></script>

app/views/foods/index.html.erb
<h1>All Result</h1>
<%= link_to 'Home', foods_home_path %>

<table id="movies">
  <thead>
    <tr>
      <th>
        <%= "Name" %>
      </th>
      <th>
        <%= "Price" %>
      </th>
      <th>
        <%= "Resto Name" %>
      </th>
      <th>
        <%= "Description" %>
      </th>
      <th>
        <%= "Tag" %>
      </th>
      <th>
        <%= "Created" %>
      </th>
      <th>
        <%= "Updated" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <th>
          <%= food.foodName %>
        </th>
        <th>
          <%= food.price %>
        </th>
        <th>
          <%= food.restoName %>
        </th>
        <th>
          <%= food.description %>
        </th>
        <th>
          <%= food.tagName %>
        </th>
        <th>
          <%= food.created_at %>
        </th>
        <th>
          <%= food.updated_at %>
        </th>
      </tr>
    <% end %>

  </tbody>
</table>

<%=# button_to "Heart", foods_home_path %>

app/views/foods/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/foods/search.html.erb
  <div align="center">
  <div class="text"></div>
 
  <%= form_tag foods_search_path, :method => 'get' do %>
  <input type="text" id="search" name="search" class="button" placeholder="Search"/>
  <%end%>
  <br>
</div>
<div class = "container">

<div class="box">

<div align="right">
        <select id="editable_pages" class="btn btn-default dropdown-toggle">
      <option selected disabled hidden >Sort by</option>
      <option value="Likes" data-edit-url="<%= foods_search_path(search: params[:search], :sort_by => 'likes') %>">Likes</option>
      <option value="Price" data-edit-url="<%= foods_search_path(search: params[:search], :sort_by => 'price') %>">Price</option>
      <option value="Name" data-edit-url="<%= foods_search_path(search: params[:search], :sort_by => 'name') %>">Name</option>
    </select>   
        </div>
        <br>

<script type="text/javascript">
    $('#editable_pages').change(function() {
    window.location = $(this).find(":selected").data('edit-url');
});
</script>

<div class = "row">
<ul class= "products" >
<% @foods.each do |food|  %>  
  
  <li>
    <%= div_for food do %>  
      <%= render :partial => 'hearts/button', :locals => {:food => food} %>
    <% end %>
  </li>

<% end %>
</ul>
</div>
</div>
</div>

<!--    
<br>
<br><br><br><br>
<div class = "container">
<div class="box"
<div class = "row">
<% @foods.each do |food| %>
  <div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
    <img src="http://www.brake.eu/images/home1.jpg" alt="">
    <div class="caption">
    <h4 class="pull-right"><%= food.price %></h4>
    <foodName><a href="#"><%= food.food_name %></a>
    </foodName>
    <desc>
    <h7><br /><br />Resto Name:  <%= food.resto_name %></h7>
    <h7><br />  Description: <%= food.description %> </h7>
    <h7><br />  Address: <%= food.address %> </h7>
                                </desc>
                            </div>
                            <div class="ratings">
                                <p >
                                <a href="#">
                                  <span class="glyphicon glyphicon-heart"></span>
                                </a>
                                </p>




                                <p class="pull-right">31 reviews</p>
                                
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>




                            </div>
                        </div>
                    </div>

  <% end %>

</div>
</div>
</div>
-->

app/views/foods/show_all.html.erb
  <div align="center">
  <div class="text"></div>
 
  <%= form_tag foods_search_path, :method => 'get' do %>
  <input type="text" id="search" name="search" class="button" placeholder="Search"/>
  <%end%>
  <br>
</div>
<head>
<!--	<title>Twitter Heart Button Animation</title>
	<link rel="stylesheet" type="text/css" href="heartstyle.css"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script>
	$(document).ready(function()
	{
    
	$('body').on("click",'.heart',function()
    {
    	
    	var A=$(this).attr("id");
    	var B=A.split("like");
        var messageID=B[1];
        var C=parseInt($("#likeCount"+messageID).html());
    	$(this).css("background-position","")
        var D=$(this).attr("rel");
       
        if(D === 'like') 
        {      
        $("#likeCount"+messageID).html(C+1);
        $(this).addClass("heartAnimation").attr("rel","unlike");
        
        }
        else
        {
        $("#likeCount"+messageID).html(C-1);
        $(this).removeClass("heartAnimation").attr("rel","like");
        $(this).css("background-position","left");
        }


    });


	});
	</script>

    -->
</head>

<div class = "container">
    
<div class="box">
 <div align="right">
        <select id="editable_pages" class="btn btn-default dropdown-toggle">
      <option selected disabled hidden >Sort by</option>
      <option value="Likes" data-edit-url="<%= foods_show_all_path(:sort_by => 'likes') %>">Likes</option>
      <option value="Price" data-edit-url="<%= foods_show_all_path(:sort_by => 'price') %>">Price</option>
      <option value="Name" data-edit-url="<%= foods_show_all_path(:sort_by => 'name') %>">Name</option>
    </select>   
        </div>
<br>

<script type="text/javascript">
    $('#editable_pages').change(function() {
    window.location = $(this).find(":selected").data('edit-url');
});
</script>


<div class = "row">
<ul class= "products">
<% @foods.each do |food|  %>  
  
  <li>
    <%= div_for food do %>
      <%= render :partial => 'hearts/button', :locals => {:food => food} %>
    <% end %>
  </li>

<% end %>
</ul>
</div>
</div>
</div>